openapi: 3.0.0
info:
  title: Simple Big Graph
  description: |
    RESTful graph API exposing the Stanford Network Analysis Platform (SNAP)

    - [Source Code](https://github.com/dgoldstein1/graphApi)
    - [SNAP](https://snap.stanford.edu/index.html)
  version: "1.0.0-oas3"
servers:
  - url: http://staging-api.example.com
    description: TODO create demo API


paths:
  /edges:
    post:
      summary: Add edges to graph. Creates neighbor nodes if they do not already exist.
      requestBody:
        description: Optional description in *Markdown*
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - neighbors
              properties:
                neighbors:
                  type: array
                  items:
                    type: string
      parameters:
        - in: query
          name: node
          schema:
            type: string
          required: true
          description: Name of node to retrieve neighbors
      responses:
        '200':
          description: A JSON array of neighbors
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EdgesResponse'

        '404':
          description: node does not exist
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EdgesResponse'

        '500':
          description: An error message.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /neighbors:
    get:
      summary: Returns a list of neighboring nodes.
      parameters:
        - in: query
          name: node
          schema:
            type: string
          required: true
          description: Name of node to retrieve neighbors
      responses:
        '200':
          description: A JSON array of neighbors
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
        '500':
          description: An error message.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'



  /shortestPath:
    get:
      summary: Returns path between two nodes, if exists.

      parameters:
        - in: query
          name: start
          schema:
            type: string
          required: true
          description: Name of the starting node.
        - in: query
          name: end
          schema:
            type: string
          required: true
          description: Name of the ending node.
      responses:
        '200':
          description: A JSON array of nodes
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
        '500':
          description: An error message.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /metrics:
    get:
      summary: Prometheus Metrics.
      responses:
        '200':
          description: Prometheus metrics. For more information see [data model](https://prometheus.io/docs/concepts/data_model/).
        '500':
          description: An error message.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /save:
    get:
      summary: Saves current graph to GRAPH_SAVE_PATH and streams file. Note that this endpoint can take 1+ minutes.
      responses:
        '200':
          description: File stream of graph as a [TF file](https://snap.stanford.edu/snappy/doc/reference/streams.html#TFIn).
        '500':
          description: An error message.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  schemas:
    EdgesResponse:
      type: object
      properties:
        neighborsAdded:
          description: new neighbors added to the current node (which were not currently there)
          type: array
          items:
            type: string
    Error:
      type: object
      properties:
        code:
          type: integer
          description: The code of the error.
        error:
          type: string
          description: Explanation of the error.
